### PR TITLE
State change signals

### PR DESCRIPTION
**Pull request by darshanrp**

### CODE REVIEW

**Comment by kerchner** [comment]
In the location_change_receiver method, please rename the variable in the NO_RESPONSE section to something more like "offline_session" (vs. login_session)

**Comment by darshanrp** [comment]
I'm using the NO_RESPONSE constant defined in the model, because the Location state is defined by that constant. Should i create a new constant with the same value?

**Comment by darshanrp** [comment]
Changed it! Sorry for the confusion

**Comment by kerchner** [comment]
Thanks!   Also, these lines in `location_change_receiver` seem to violate the respective columns' non-null constraints, when I tested:

```
instance.last_login_start_time = None
```

and

```
instance.last_offline_start_time = None
```

I would be comfortable just removing these lines, since leaving the current values in these attributes would not actually be inaccurate/untrue data.

**Pull request merged**
